### PR TITLE
Add devcontainer support

### PR DESCRIPTION
**Pull request by dingyuchen**
### Summary:
For a more seamless onboarding experience, we can consider using Dev Containers which sets up a reproducible development environment with minimal setup steps.

We can support Dev Containers for the CATcher Guides first, and if dev feedback is positive, consider adding support for main repo.

### Changes Made:
* Add an Ubuntu container with `fish` shell and `node16`
* Add guide in README for setting up dev box

### Proposed Commit Message:
```
Add DevContainer to repo
```

### CODE REVIEW

**Comment by kkangs0226** [comment]
Sounds like a good idea, we can definitely try this out

**Review by kkangs0226 — APPROVED** [review]

**Comment by tlylt** [comment]
Hey @kkangs0226, sorry for the ping.

I'm hoping to seek feedback from CATcher developers on whether this setup has worked  well for you guys when maintaining your documentation (which is built with MarkBind). It's of particular interest to MarkBind devs as to whether this dev container setup is better than the suggested workflows of using MarkBind as listed [here](https://markbind.org/userGuide/gettingStarted.html).

Appreciate if there are any feedback/suggestions/thoughts on the above, thank you!

**Comment by kkangs0226** [comment]
@tlylt I have not had a chance to work on the documentation, @CATcher-org/developers developers who have tried it out please give some comments! 
I will test it out in the coming days.

**Comment by chunweii** [comment]
@tlylt I tried it and it works for me. It's not complicated, and it could be helpful if I have multiple versions of markbind installed. I would recommend it as an alternative to the existing method

**Comment by tlylt** [comment]
> and it could be helpful if I have multiple versions of markbind installed.

Thanks for sharing! Just to add in case it's of interest to you, markbind can also work like any other npm packages with a local installation of markbind-cli in the respective repository, which will allow for different markbind version in different projects.

**Pull request merged**
