### PR TITLE
Configure plain Markbind site

### PR DESCRIPTION
**Pull request by ptvrajsk**
Proposed Commit Message:
```
Configured Plain Markbind Site

Previously, a jekyll themed markdown rendering was used
to display content on the github pages site. This has been
changed to support Markbind.
```

### CODE REVIEW

**Review by seanlowjk — APPROVED** [review]
:+1: Thanks for the PR Mr Raj ><

**Comment by anubh-v** [comment]
Can you include some instructions on how we can test this locally?

**Comment by ptvrajsk** [comment]
> Can you include some instructions on how we can test this locally?
> (I'm getting some errors when following the [`Start with an existing project`](https://markbind.org/userGuide/gettingStarted.html) section of the Markbind user guide, is this the right process?)

Yes sure, but could I know what the error you faced was?

**Review by anubh-v — APPROVED** [review]

**Comment by anubh-v** [comment]
@ptvrajsk - sorry, my mistake - there was a problem with my Markbind installation.
Got it working :+1:

**Comment by ptvrajsk** [comment]
> @ptvrajsk - sorry, my mistake - there was a problem with my Markbind installation.
> Got it working 👍

Shall I put a summary of the instructions on running markbind as a part of the `README.md` in a separate PR?

**Comment by anubh-v** [comment]
> Shall I put a summary of the instructions on running markbind as a part of the README.md in a separate PR?

Sure, but we can keep it brief -- just a statement that we're using Markbind and a link to Markbind's guide will work.

**Pull request merged**
