### PR TITLE
DG: Add info about Pull Request Templates

### PR DESCRIPTION
**Pull request by kkangs0226**
Summary:
Fixes https://github.com/CATcher-org/CATcher/issues/719

Changes made: 
- Added guideline on what to include for PR message
- Added sample PR template for new developers' reference 

Proposed commit message: 
```
DG: Add info about pull request template

New developers are not familiar with submitting PRs for CATcher
and use different structures, which reduces efficiency when
reviewing PRs.

Let's
* add guidelines for PR content
* advise contributors to use the auto-generated PR template
```

### CODE REVIEW

**Comment by kkangs0226** [comment]
I'm not sure whether I should link to existing PRs, or if the sample template is sufficient. Let me know on your thoughts! @CATcher-org/2021-devs

**Comment by anubh-v** [comment]
Thanks @kkangs0226 

However, perhaps we can add a PR template file directly on our CATcher repo, [as shown here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) ?

This would automatically populate the template's content whenever a new PR is created.

**Comment by kkangs0226** [comment]
@anubh-v I didn't know we could add a template file, sounds like a good idea! Do we need to add the template file to both github pages repo and our main repo?

**Comment by anubh-v** [comment]
> Do we need to add the template file to both github pages repo and our main repo?

I guess we can add a template file to both, to help contributors on both repos
(I'm not sure if there's a way to use a single template file for both repos)

**Comment by kkangs0226** [comment]
I have created a new repository `.github` and added the PR template file `pull_request_template.md`. I have checked that the PR template is generated automatically when a PR is created on any repository under CATcher. It would be good if we could include default issue template in this repository as well (can be done in a separate PR)!

I have also removed the template from the developer notes since it is now redundant.

Please let me know if there are any changes to be made to the PR template!

**Review by anubh-v — APPROVED** [review]

**Pull request merged**
